export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ";
export const PRODUCT_LIST_SUC = "PRODUCT_LIST_SUC";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQ = "PRODUCT_DETAILS_REQ";
export const PRODUCT_DETAILS_SUC = "PRODUCT_DETAILS_SUC";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_DELETE_REQ = "PRODUCT_DELETE_REQ";
export const PRODUCT_DELETE_SUC = "PRODUCT_DELETE_SUC";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_CREATE_REQ = "PRODUCT_CREATE_REQ";
export const PRODUCT_CREATE_SUC = "PRODUCT_CREATE_SUC";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_UPDATE_REQ = "PRODUCT_UPDATE_REQ";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_REQ = "PRODUCT_CREATE_REVIEW_REQ";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_TOP_RATED_REQ = "PRODUCT_TOP_RATED_REQ";
export const PRODUCT_TOP_RATED_SUCCESS = "PRODUCT_TOP_RATED_SUCCESS";
export const PRODUCT_TOP_RATED_FAIL = "PRODUCT_TOP_RATED_FAIL";
